/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import persistencia.AgendaDao;
import persistencia.Conexao;
import cadastro.Agenda;
import Interface.JanelaCadastro;
import Interface.JanelaListagem;
import estoque.Produto;
import estoque.ProdutoDao;
import java.awt.Color;

/**
 *
 * @author Lucas
 */
public class JanelaListagem extends javax.swing.JPanel {

    /**
     * Creates new form TelaListagem
     */
    public JanelaListagem() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
      Agenda   age ;
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableContatos = new javax.swing.JTable();
        bntListar = new javax.swing.JButton();
        btnConsultar = new javax.swing.JButton();
        txtConsultarNome = new javax.swing.JTextField();
        btnApagar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtCpf = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtTelefoneResidencial = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtTelefoneCelular = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtTelefone = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btnAlterar = new javax.swing.JButton();

        jTableContatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "CPF", "Telefone Resencial", "Telefone Celular", "Telefone"
            }
        ));
        jTableContatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableContatosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableContatos);

        bntListar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfacegrafica/pesquisar.jpg"))); // NOI18N
        bntListar.setText("LISTAR");
        bntListar.setToolTipText("Clique em aqui para consultar todos os cadastro");
        bntListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntListarActionPerformed(evt);
            }
        });

        btnConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/pesquisar.jpg"))); // NOI18N
        btnConsultar.setText("CONSULTAR");
        btnConsultar.setToolTipText("Clique aqui para consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        txtConsultarNome.setToolTipText("Digite um Nome aqui para pesquisa");

        btnApagar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/limpar.png"))); // NOI18N
        btnApagar.setText("APAGAR");
        btnApagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApagarActionPerformed(evt);
            }
        });

        jLabel1.setText("Nome:");

        jLabel2.setText("CPF:");

        jLabel3.setText("Telefone Residencial:");

        jLabel4.setText("Telefone Celular:");

        jLabel5.setText("Telefone:");

        jLabel6.setText("ID:");

        txtId.setEditable(false);

        jLabel7.setText("Nome:");

        btnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/confirmar.png"))); // NOI18N
        btnAlterar.setText("ALTERAR");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 726, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bntListar, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(txtConsultarNome, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(btnConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnApagar, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAlterar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtTelefoneResidencial)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(txtTelefoneCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(txtTelefone))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(52, 52, 52))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bntListar)
                    .addComponent(btnConsultar)
                    .addComponent(txtConsultarNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtTelefoneCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtTelefoneResidencial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnApagar)
                    .addComponent(btnAlterar)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bntListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntListarActionPerformed
        // TODO add your handling code here:
        btnConsultar.setToolTipText("Informe o nome para consulta");

        try {

            AgendaDao produto = new AgendaDao();
            Agenda pr = new Agenda();
            JanelaCadastro pw = new JanelaCadastro();

            ArrayList dados = produto.listar();
            DefaultTableModel model = (DefaultTableModel) jTableContatos.getModel();
            model.setNumRows(0);
            for (int pos = 0; pos < dados.size(); pos++) {
                String[] saida = new String[6];//novo
                Agenda aux = (Agenda) (dados.get(pos));//novo

                // String conversao = pr.setQtdEstoque(Double.parseDouble(aux.getQtdEstoque()));
                saida[0] = "" + aux.getId();
                saida[1] = aux.getNome();//novo
                saida[2] = aux.getCpf();
                saida[3] = aux.getTel_resid();
                saida[4] = aux.getTel_cel();
                saida[5] = aux.getFone();

                //Incluir nova linha na Tabela
                model.addRow(saida);//novo
            }

        } catch (Exception erro) {
            //JOptionPane.showMessageDialog(rootPane, erro.getMessage());
            System.out.println(erro.getMessage());
        }
    }//GEN-LAST:event_bntListarActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        // TODO add your handling code here:

        AgendaDao p = new AgendaDao();
        Agenda pr = new Agenda();
        try {

            String dados = txtConsultarNome.getText();
            Agenda dados1 = p.consultar(dados);
            DefaultTableModel model = (DefaultTableModel) jTableContatos.getModel();
            model.setNumRows(0);
            Agenda aux = (Agenda) (dados1);

            String[] saida = new String[6];
            saida[0] = "" + aux.getId();//novo
            saida[1] = aux.getNome();//novo
            saida[2] = aux.getCpf();
            saida[3] = aux.getTel_resid();
            saida[4] = aux.getTel_cel();
            saida[5] = aux.getFone();

            model.addRow(saida);

        } catch (Exception erro) {
            //JOptionPane.showMessageDialog(rootPane, erro.getMessage());
            System.out.println(erro.getMessage());
        }

    }//GEN-LAST:event_btnConsultarActionPerformed

    private void btnApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApagarActionPerformed
        // TODO add your handling code here:
        try {

            AgendaDao ag = new AgendaDao();
            int id = Integer.parseInt(txtId.getText());

            ag.deletar(id);

        } catch (Exception error) {
            System.out.println(error.getMessage());

        }
        JOptionPane.showMessageDialog(null, "Deseja Realmente deletar o registro do " + txtNome.getText() + " Com ID " + txtId.getText());

        int linhaSelecionada = jTableContatos.getSelectedRow();
        if (jTableContatos.getSelectedRow() != -1) {

            ((DefaultTableModel) jTableContatos.getModel()).removeRow(jTableContatos.getSelectedRow());
            int nome = jTableContatos.getSelectedRow();

            // jTableContatos.getModel().getValueAt(  jTableContatos.getSelectedRow() ,0);
            txtCpf.setText("");
            txtId.setText("");
            txtNome.setText("");
            txtTelefone.setText("");
            txtTelefoneCelular.setText("");
            txtTelefoneResidencial.setText("");
            int quantosResgistro = jTableContatos.getRowCount();
            if (quantosResgistro > linhaSelecionada) { //posicionar o cursor no proxima linha
                jTableContatos.setRowSelectionInterval(linhaSelecionada, linhaSelecionada);
            } else if (jTableContatos.getRowCount() > 0) { //poscionar o  cursor sempre no elemento existente
                jTableContatos.setRowSelectionInterval(linhaSelecionada - 1, linhaSelecionada - 1); //posicionar o cursos no elemento anterior caso seja o ultimo a ser excluido
            }

        } else {
            JOptionPane.showMessageDialog(null, "SORRY, ALL RESGISTRATION ARE EXLCUDED ", null, JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnApagarActionPerformed

    private void jTableContatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableContatosMouseClicked
        // TODO add your handling code here:

        int linha_selecionada = jTableContatos.getSelectedRow();
        txtId.setText(jTableContatos.getValueAt(linha_selecionada, 0).toString());
        txtNome.setText(jTableContatos.getValueAt(linha_selecionada, 1).toString());
        txtCpf.setText(jTableContatos.getValueAt(linha_selecionada, 2).toString());
        txtTelefoneResidencial.setText(jTableContatos.getValueAt(linha_selecionada, 3).toString());
        txtTelefoneCelular.setText(jTableContatos.getValueAt(linha_selecionada, 4).toString());
        txtTelefone.setText(jTableContatos.getValueAt(linha_selecionada, 5).toString());

    }//GEN-LAST:event_jTableContatosMouseClicked

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        // TODO add your handling code here:
        
        try {
            AgendaDao ag = new AgendaDao();
           
            
            age.setId(Integer.parseInt(txtId.getText()));
            
            age.setNome(txtId.getText());
          //  age.setCpf(txtId.getText());
          //  age.setTel_resid(txtId.getText());
          //  age.setTel_cel(txtId.getText());
          //  age.setFone(txtId.getText());
            
          
            ag.alterar(age);
             JOptionPane.showMessageDialog(txtNome, " Foi Alterado o nome com sucesso");
            
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnAlterarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntListar;
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnApagar;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableContatos;
    private javax.swing.JTextField txtConsultarNome;
    private javax.swing.JTextField txtCpf;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtTelefone;
    private javax.swing.JTextField txtTelefoneCelular;
    private javax.swing.JTextField txtTelefoneResidencial;
    // End of variables declaration//GEN-END:variables
}
